project/base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

project/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:slug>/', views.post, name='item'),
    path('add/post/', views.add_post, name='add_post'),
    path('edit/post/<int:pk>/', views.edit_post, name='edit_post'),
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from . import settings
from base import views
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('accounts/register/', views.Register.as_view(), name='register'),
    path('accounts/change/<int:pk>/', views.UserChange.as_view(), name='user_change'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += i18n_patterns(
    path('', include('base.urls')),
    path('blog/', include('blog.urls')),
    path('tags/<slug:slug>/', views.tag, name='tag'),
    path('search/', include('search.urls')),
    path('about/', views.about, name='about'),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.text import slugify
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFit


class Post(models.Model):
    title = models.CharField(max_length=255, default='', unique=True)
    slug = models.SlugField(default='', blank=True)
    post_date = models.DateTimeField(auto_now_add=True, null=True)
    updated_date = models.DateTimeField(auto_now=True, null=True)
    description = models.TextField(default='', blank=True)
    body = models.TextField(default='', blank=True)
    image = models.ImageField(default='', blank=True, upload_to='post_images')
    image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFit(250, 250)],
                                     format='JPEG', options={'quality': 60})
    image_large = ImageSpecField(source='image', processors=[ResizeToFit(700, 700)],
                                 format='JPEG', options={'quality': 60})

    class Meta:
        ordering = ['-post_date']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        return reverse('item', args=[str(self.slug)])

project/blog/models/post.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.text import slugify
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFit
from django.contrib.auth.models import User
from .tag import *


class Post(models.Model):
    title = models.CharField(max_length=255, default='', unique=True)
    slug = models.SlugField(default='', blank=True)
    post_date = models.DateTimeField(auto_now_add=True, null=True)
    updated_date = models.DateTimeField(auto_now=True, null=True)
    description = models.TextField(default='', blank=True)
    body = models.TextField(default='', blank=True)
    image = models.ImageField(default='', blank=True, upload_to='post_images')
    image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFit(250, 250)],
                                     format='JPEG', options={'quality': 60})
    image_large = ImageSpecField(source='image', processors=[ResizeToFit(700, 700)],
                                 format='JPEG', options={'quality': 60})
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-post_date']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        return reverse('item', args=[str(self.slug)])

project/blog/models/tag.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Tag(models.Model):
    title = models.CharField(max_length=255, default='')
    slug = models.SlugField(default='', blank=True)

    class Meta:
        ordering = ['title']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        return reverse('tag', args=[str(self.slug)])

project/blog/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['author']

project/blog/views.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect

from blog.forms import PostForm
from blog.models import Post

def post(request, slug=None):
    item = get_object_or_404(Post, slug=slug)
    return render(request, 'blog/post.html', {'item': item, 'title': item,})

@permission_required('blog.add_post')
def add_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.author = request.user
            item.save()
            form.save_m2m()
            return redirect(item.get_absolute_url())
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {'form': form, 'title': 'Add post',})

@permission_required('blog.edit_post')
def edit_post(request, pk=None):
    item = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST or None, request.FILES or None, instance=item)
        if form.is_valid():
            form.save()
            return redirect(item.get_absolute_url())
    else:
        form = PostForm(instance=item)

    title = 'Edit: %s' % item
    return render(request, 'blog/post_form.html', { 'form': form, 'item': item, 'title': title })

project/blog/templates/blog/post.html
{% extends 'base/base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block h1 %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
    <div class="post">
       <span class="post-author">By <strong>
        {% if item.author.profile.display_name %}
            {{ item.author.profile.display_name }}
        {% else %}
            {{ item.author }} {% endif %}</strong>
       </span>
        <span class="post-date">{{ item.post_date |date:"M d, Y" }}</span>
        {% if perms.blog.change_post %}
            | <a class="post-edit" href="{% url 'edit_post' item.id %}">Edit</a>
        {% endif %}
        <div class="post-description clearfix">{{ item.description }}</div>
        {% if item.image %}
            <img alt="post-image" class="post-image" src="{{ item.image_large.url }}">
        {% endif %}
        <div class="post-body">{{ item.body }}</div>
        {% if item.tags %}
            <ul class="tags">
                {% for tag in item.tags.all %}
                    <li class="tags-tag">
                        <a class="tags-tag-a" href="{% url 'tag' tag.slug %}">{{ tag }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

project/blog/templates/blog/post_form.html
{% extends 'base/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block h1 %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<form class="post-form" method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}
    {{ form }}
    <input class="post-form-submit submit" type="submit" value="Save">
</form>

{% endblock %}